export function aiGuideText(): string {
  return [
    "# vspec AI Guide",
    "",
    "## 작성 원칙",
    "",
    "- 사용자의 요청, PRD, 기존 문서가 한국어이면 use case 본문도 한국어로 작성한다.",
    "- 파일명, key, actor/stakeholder `name` 같은 식별자는 영문 kebab-case로 쓴다 (예: `user`, `cli-agent`).",
    "- **actor/stakeholder를 참조할 때는 display_name이 아니라 `name`(영문 slug)을 쓴다.** doctor는 `name`만 인식한다.",
    "  예: `1. **user** 계정을 연동한다.` (O) / `1. **사용자** 계정을 연동한다.` (X — display_name이라 인식 안 됨).",
    "- **title은 동사구(목표)로 쓴다.** 예: `주문을 생성한다`, `GitHub 계정을 연동한다`.",
    "  명사형 종결(`...등록`, `...확인`, `...생성`, `...주입`)은 피한다 — `...등록한다`처럼 동사로 끝낸다.",
    "- title, stakeholder interest, precondition, trigger, scenario step의 동작 텍스트, extension, guarantee, notes는 사용자의 언어를 따른다 (단, 위의 actor/stakeholder 참조 이름은 영문 slug).",
    "- 모든 scenario step은 E2E 테스트의 When/Then으로 옮길 수 있을 만큼 관찰 가능한 행동과 결과를 담는다.",
    "- `specs/glossary.md`의 Preferred Terms를 우선 사용하고 Avoid Terms의 모호한 표현을 피한다.",
    "",
    "## 기본 흐름",
    "",
    "1. 저장소 루트에서 `vspec init --key VSPEC`를 실행한다.",
    "2. 참조 actor를 `vspec actor create --name developer --display-name \"개발자\"`로 만든다.",
    "3. 참조 stakeholder를 `vspec stakeholder create --name vooster --display-name \"Vooster\"`로 만든다.",
    "4. `vspec usecase create --title \"유스케이스를 작성한다\" --primary-actor developer`로 use case를 시작한다.",
    "5. markdown을 직접 편집하거나 `vspec usecase add-stakeholder`, `vspec step add`, `vspec usecase set`을 사용한다.",
    "6. `vspec doctor <KEY>`를 실행해 오류와 품질 경고를 확인한다.",
    "7. 준비되면 `vspec export gherkin <KEY>`로 feature 파일을 만든다.",
    "",
    "## 유효한 enum 값",
    "",
    "아래 값 외에는 `vspec usecase set` 이 거절하므로 반드시 정확히 입력한다.",
    "",
    "| 필드       | 유효한 값                                    | 비고                                     |",
    "|------------|----------------------------------------------|------------------------------------------|",
    "| `level`    | USER_GOAL \\| SUMMARY \\| SUBFUNCTION          | CLI 플래그: user-goal\\|summary\\|subfunction |",
    "| `format`   | BRIEF \\| CASUAL \\| FULLY_DRESSED             | 작성 시작은 BRIEF, 모든 필드를 채우면 FULLY_DRESSED |",
    "| `status`   | DRAFT \\| IN_REVIEW \\| APPROVED \\| DEPRECATED | 기본값은 DRAFT                           |",
    "| `priority` | P0 \\| P1 \\| P2 \\| P3                         | CLI 플래그: p0\\|p1\\|p2\\|p3              |",
    "",
    "예시:",
    "",
    "```",
    "vspec usecase set UC-001 --field status --value IN_REVIEW",
    "vspec usecase set UC-001 --field priority --value P1",
    "vspec usecase set UC-001 --field level --value USER_GOAL",
    "```",
    "",
    "잘못된 값(예: `--value p1`, `--value in_review`)을 입력하면 CLI가 오류를 반환하고 파일은 변경되지 않는다.",
    "",
    "## Extensions(확장) 작성법",
    "",
    "Extension은 메인 성공 시나리오에서 벗어나는 분기 — 오류, 대안 흐름, 예외 — 를 정의한다.",
    "가장 흔한 혼동의 원인이므로 아래 규칙을 숙지한다.",
    "",
    "### 확장 포인트 ID 규칙",
    "",
    "- `3a` = 메인 시나리오 3번 스텝에서 분기하는 첫 번째 대안",
    "- `3b` = 동일 스텝에서 두 번째 대안",
    "- `*a` = 임의의 단계에서 발생할 수 있는 첫 번째 대안 (예: 세션 만료)",
    "- Outcome은 `SUCCESS | FAILURE | PARTIAL` 중 하나. 명시하지 않으면 기본값은 `FAILURE`.",
    "- 메인 시나리오로 복귀하면 Outcome 자유 텍스트에 `rejoins main at step N`을 적는다.",
    "",
    "### 방법 1 — CLI 사용",
    "",
    "```",
    "# 확장 시나리오를 추가한다",
    "vspec scenario add UC-001 --type extension --at 3a --condition \"결제 수단이 거절되면\" --outcome failure",
    "",
    "# 확장 시나리오에 핸들링 스텝을 추가한다",
    "vspec step add UC-001 --scenario 3a --actor system --action \"거절 사유를 표시한다\"",
    "vspec step add UC-001 --scenario 3a --actor customer --action \"다른 결제 수단을 선택한다\"",
    "```",
    "",
    "### 방법 2 — 마크다운 직접 편집 (권장, 가장 유연함)",
    "",
    "`specs/usecases/<KEY>-*.md` 파일의 `## Extensions` 섹션을 직접 작성한다.",
    "아래 블록 구조를 그대로 따른다:",
    "",
    "```markdown",
    "## Extensions",
    "",
    "### 3a. 결제 수단이 거절되면",
    "- 3a1. **System** 거절 사유를 표시한다.",
    "- 3a2. **Customer** 다른 결제 수단을 선택한다.",
    "- (Outcome: FAILURE — 유스케이스를 종료한다.)",
    "",
    "### 3b. 재고가 부족하면",
    "- 3b1. **System** 재고 부족 메시지를 표시한다.",
    "- 3b2. **Customer** 수량을 줄이거나 취소를 선택한다.",
    "- (Outcome: PARTIAL — rejoins main at step 2.)",
    "",
    "### *a. 세션이 만료되면",
    "- *a1. **System** 재로그인을 요구한다.",
    "- (Outcome: PARTIAL — rejoins main at step 2.)",
    "```",
    "",
    "포맷 규칙:",
    "",
    "- 확장 헤더: `### <단계><글자>. <조건>` (예: `3a`, `3b`, `*a`)",
    "- 핸들링 스텝: `- <id>. **Actor** <동작>.` (id는 `3a1`, `3a2`, `*a1` 등)",
    "- Outcome 줄: `- (Outcome: SUCCESS|FAILURE|PARTIAL — <자유 텍스트>)`",
    "- 메인 시나리오로 복귀하는 경우 자유 텍스트에 `rejoins main at step N` 형태로 적는다.",
    "- Outcome 줄을 생략하면 파서는 해당 확장을 `FAILURE`로 간주한다.",
    "",
    "## 마크다운 직접 편집이 1급 경로",
    "",
    "`vspec scenario add`, `vspec step add`, `vspec usecase set` 같은 mutator 명령은 편의 기능일 뿐이다.",
    "`specs/usecases/<KEY>-*.md` 파일을 직접 편집하는 것이 완전히 지원되는 기본 작성 방식이다.",
    "복잡한 Extensions, 긴 Notes, 세밀한 문체 조정은 직접 편집이 훨씬 효율적이다.",
    "",
    "### 인식되는 섹션 제목 (정확히 일치해야 한다)",
    "",
    "| 섹션 제목                        | 설명                           |",
    "|----------------------------------|--------------------------------|",
    "| `## Stakeholders and Interests`  | 이해관계자와 관심사            |",
    "| `## Preconditions`               | 선행 조건                      |",
    "| `## Trigger`                     | 유스케이스를 시작하는 이벤트   |",
    "| `## Main Success Scenario`       | 메인 성공 시나리오 스텝 목록   |",
    "| `## Extensions`                  | 확장(대안/예외) 시나리오       |",
    "| `## Success Guarantee`           | 성공 시 보장 조건              |",
    "| `## Minimal Guarantee`           | 실패 시에도 보장되는 최소 조건 |",
    "| `## Notes`                       | 자유 형식 메모                 |",
    "",
    "메인 시나리오 스텝 형식: `1. **<actor-name>** <동작>.` — 번호 + 굵은 actor `name`(영문 slug) + 동작. 동작은 사용자의 언어로, actor 이름은 영문 slug로 쓴다.",
    "",
    "직접 편집 후에는 반드시 `vspec doctor <KEY>`로 검증한다.",
    "",
    "Files under `specs/` are the source of truth. 서버, 데이터베이스, 네트워크 서비스 없이 로컬 파일만 사용한다.",
  ].join("\n");
}
